<?php

return [
    'sign_in' => 'Sign In',
    'go_to_login' => 'Go to Login',
    'failed' => 'No account matching those credentials could be found.',

    'forgot_password' => [
        'label' => 'Zapomniałeś hasła?',
        'label_help' => 'Wpisz swój E-Mail, a wyślemy ci link do resetowania hasła.',
        'button' => 'Odzyskaj konto',
    ],

    'reset_password' => [
        'button' => 'Reset and Sign In',
    ],

    'two_factor' => [
        'label' => 'Token 2-FA',
        'label_help' => 'This account requires a second layer of authentication in order to continue. Please enter the code generated by your device to complete this login.',
        'checkpoint_failed' => 'The two-factor authentication token was invalid.',
    ],

    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
    'password_requirements' => 'Password must be at least 8 characters in length and should be unique to this site.',
    '2fa_must_be_enabled' => 'The administrator has required that 2-Factor Authentication be enabled for your account in order to use the Panel.',
];
